### PR TITLE
Nathan burns Peer Review

### PR DESCRIPTION
**Pull request by NathanBurns3**
Peer Review Changes

### CODE REVIEW

**Comment by NathanBurns3** [comment]
### Changes
- Added JavaDoc comments to the class and methods.
- Added the fetchAll method to the IUserService interface.
- Implemented the fetchAll method in the UserServiceStub class. 
- Proper exception handling was implemented in the saveUser method. 
- Ensured dependency injection is correctly set up.

**Comment by NathanBurns3** [comment]
### Analysis
**Was the program available in UC Github on time?** 
The program was available on time 

**Is the program easy for you, as an outsider, to understand?** 
The program is relatively easy to understand, but the lack of JavaDoc comments makes it harder to grasp the purpose of some methods. 

**Does the program compile?** 
The program does compile

**Comment by NathanBurns3** [comment]
### What I learned
- Stub files are used to simulate the behavior of complex objects, often in testing, to provide responses to method calls
- Proper JavaDoc comments help in understanding the purpose and usage of classes and methods.
- A ResponseEntity is a spring class that represents the entire HTTP response, allowing for more control over the response returned from a controller

**Comment by Wellmacj** [comment]
@MiniWilford Is this good to merge?

**Comment by Wellmacj** [comment]
@JoshNoiman Are you cool with merging this?

**Pull request closed without merging**
